const actions = {
	types: {
		EDIT_TODO: 'EDIT_TODO',
		ADD_TODO: 'ADD_TODO',
		DONE_EDITING_TODO: 'DONE_EDITING_TODO',
		START_EDITING_TODO: 'START_EDITING_TODO',
		UNDO_EDITING_TODO: 'UNDO_EDITING_TODO',
		DELETE_TODO: 'DELETE_TODO',
		TOGGLE_TODO: 'TOGGLE_TODO',
		TOGGLE_ALL: 'TOGGLE_ALL',
		CLEAR_COMPLETED: 'CLEAR_COMPLETED',
		SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER'
	}
}

export default actions;
